---
- name: Install dependencies
  yum:
    name:
      - wget
      - tar
    state: present

- name: Create doc root
  file: { path: /var/www/html, state: directory, owner: nginx, group: nginx, mode: '0755' }

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    creates: /var/www/html/wordpress

- name: Ensure wp-content dir exists (EFS mount)
  file:
    path: /var/www/html/wordpress/wp-content
    state: directory
    owner: nginx
    group: nginx
    mode: '0775'

- name: Install SSM/Collections dependency
  ansible.builtin.meta: noop

- name: Place wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: nginx
    group: nginx
    mode: '0640'

- name: Set ownership
  file:
    path: /var/www/html/wordpress
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
